# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  # Agent VM image name 
  vmImageName: 'windows-2019'

  # service connection (azure)
  azureServiceConnection: 'Condeco-tenant-connection'

  # you can chose to add this in the GUI
  customerSubscriptionId: 'ALL'

stages:
  - stage: Build
    displayName: copy files (build)

    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: $(vmImageName)
      
      steps:
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)'
          artifact: 'drop'
          publishLocation: 'pipeline'
  
  - stage: Deploy
    displayName: 'Deploy stage'
    dependsOn: Build
    jobs:
    - deployment: DeployResources
      displayName: 'Deploying Az resources'
      pool:
        vmImage: $(vmImageName)
      environment: $(customerSubscriptionId)

      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzurePowerShell@4
              displayName: 'Demo storage account'
              enabled: false
              inputs:
                azureSubscription: '$(azureServiceConnection)'
                ScriptType: 'FilePath'
                ScriptPath: '$(Pipeline.Workspace)/drop/ARM-Templates/storage-account/deploy.ps1'
                ScriptArguments: '-subscriptionId $(customerSubscriptionId)'
                azurePowerShellVersion: 'LatestVersion'
                workingDirectory: '$(Pipeline.Workspace)/drop/'
                pwsh: true
            # - task: AzurePowerShell@4
            #   displayName: 'Demo storage account'
            #   inputs:
            #     azureSubscription: '$(azureServiceConnection)'
            #     ScriptType: 'FilePath'
            #     ScriptPath: '$(Pipeline.Workspace)/drop/ARM-Templates/storage-account/deploy.ps1'
            #     ScriptArguments: '-subscriptionId $(customerSubscriptionId) -workingDirectory $(System.DefaultWorkingDirectory)'
            #     azurePowerShellVersion: 'LatestVersion'
            #     workingDirectory: '$(Pipeline.Workspace)/drop/'
            #     pwsh: true